services:
  db_test:
    image: postgres:15-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: greendesk_test
    ports:
      - "5433:5432"      
    tmpfs:
      - /var/lib/postgresql/data   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d greendesk_test"]
      interval: 3s
      timeout: 3s
      retries: 10

  test:
    build: .
    container_name: fastapi_test
    volumes:
      - .:/code
    env_file:
      - .env.test
    environment:
      - DB_HOST=db_test
      - DB_PORT=5432
      - DB_NAME=greendesk_test
    command: >
      sh -c "
        echo 'Esperando a la base de datos...' &&
        python -m pytest tests/ -v --cov=app --cov-report=term-missing --cov-report=html
      "
    depends_on:
      db_test:
        condition: service_healthy

volumes: {}